stages:
  - build
  - test
  - release

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY:latest

build:
  stage: build
  script:
    - make check.env
    - make build
  tags:
    - shell

test:
  stage: test
  script:
    - echo "test"
  tags:
    - shell

release-image:
  stage: release
  script:
    - make release
  tags:
    - shell
  only:
    - master
